name: Deploy Supabase Functions

on:
  push:
    branches:
      - main
    paths:
      - "supabase/functions/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Supabase CLI
        run: |
          wget -qO- https://github.com/supabase/cli/releases/download/v1.204.4/supabase_1.204.4_linux_amd64.tar.gz | tar -xz
          sudo mv supabase /usr/local/bin/

      - name: Check Supabase CLI version
        run: supabase --version

      - name: Deploy Supabase Functions
        run: supabase functions deploy --project-ref $PROJECT --no-verify-jwt --debug
        env:
          PROJECT: myrwcjurblksypvekuzb
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
